name: drizzle

services:
  db:
    image: postgres:16.2
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql"
    restart: unless-stopped

volumes:
  postgres_data:
